apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - hpa.yaml

commonLabels:
  app: go-app
  managed-by: kustomize

images:
  - name: hello-api
    newName: hello-api
    newTag: latest
