apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  labels:
    app: go-app
  annotations:
    # IRSA annotation will be added via overlay patch
    # eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<role-name>
